import java.lang.reflect.Array;
import java.util.Arrays;

/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
 */
public class Main {
    public static void main(String[] args) {
        String s = "abcd";
        String t = "abcde";
        System.out.println(difference(s,t));
    }

    public static char difference(String s, String t){
        char[] s1 = s.toCharArray();
        char[] t1 = t.toCharArray();
        Arrays.sort(s1);
        Arrays.sort(t1);
        for(int i=0;i<s1.length;i++){
            if(s1[i]!=t1[i]) return t1[i];
        }
        return t1[t1.length-1];
    }
}
